import React from 'react';
import './toolBuilder.css';

const specUrl = 'https://github.com/WickedWicket373/startup/blob/main/tool-spec.md';

const spec = `{
  "specVersion": 1,
  "id": "tool_revenue_at_risk",
  "clientId": "acme-retail",
  "name": "Revenue at risk",
  "prompt": "Show me which Acme customers are likely to churn next month, with revenue at risk.",
  "widget": {
    "type": "stat_card",
    "value": { "field": "revenue_at_risk", "format": "currency_compact" },
    "caption": "across 14 accounts",
    "series": {
      "field": "revenue_at_risk_weekly",
      "groupBy": "week",
      "buckets": 8,
      "highlightLast": true
    }
  },
  "dataSource": "stripe",
  "filters": [
    { "field": "churn_risk", "op": "gte", "value": 0.6 }
  ],
  "dateRange": "next_30_days",
  "refresh": "hourly",
  "visibility": "draft",
  "createdBy": "agent:claude",
  "createdAt": "2026-09-10T18:04:00Z"
}`;

export function ToolBuilder() {
  return (
    <main className="grid grid-cols-1 lg:grid-cols-[260px_minmax(0,1fr)_260px] gap-4 items-start flex-1">
      <section className="tool-header lg:col-span-3">
        <h1>Retention Report</h1>
        <p>Tool · Acme Retail · Draft</p>
        <p>
          The Tool Builder is where an agency team member describes a dashboard
          widget in plain English, watches the AI turn it into a live preview,
          and publishes it to a specific client's portal. Nothing here writes
          code — the AI can only choose from a fixed set of widget types and
          known data fields, described in <a href={specUrl}>tool-spec.md</a>.
        </p>
      </section>

      <section className="describe-tool lg:col-start-1 lg:row-start-2" aria-label="Describe the tool">
        <h2>Describe the tool</h2>
        {/* PLACEHOLDER: 3rd-party API — replaced by a live call to the Anthropic Claude API at the Service deliverable */}
        <form>
          <p>
            <label htmlFor="prompt">What should this tool do?</label>
            <br />
            <textarea
              id="prompt"
              name="prompt"
              rows={4}
              cols={50}
              defaultValue="Show me which Acme customers are likely to churn next month, with revenue at risk."
            ></textarea>
          </p>
          <p>
            <button type="button">Regenerate</button>
          </p>
        </form>
      </section>

      <section className="data-sources lg:col-start-1 lg:row-start-3" aria-label="Data sources">
        <h2>Data sources</h2>
        <ul>
          <li>Stripe — synced</li>
          <li>HubSpot — synced</li>
          <li>Intercom — synced</li>
          <li>GA4 — needs auth</li>
        </ul>
      </section>

      <section className="build-steps lg:col-start-1 lg:row-start-4" aria-label="Build steps">
        <h2>Build steps</h2>
        {/* PLACEHOLDER: 3rd-party API — the checklist the Claude API reports back while generating this tool */}
        <ol>
          <li>Read churn signals from Stripe + Intercom — done</li>
          <li>Score 348 accounts by risk — done</li>
          <li>Choose a layout for the report — in progress</li>
        </ol>
      </section>

      <section className="canvas lg:col-start-2 lg:row-start-2 lg:row-span-3" aria-label="Canvas">
        <h2>Canvas</h2>

        <article className="widget-preview" aria-label="Revenue at risk widget, selected">
          <h3>Revenue at risk</h3>
          <p>Next 30 days · generated by AI</p>
          {/* PLACEHOLDER: 3rd-party API — this widget's numbers are what the Anthropic Claude API returned for the prompt above */}
          <p className="big-number">
            $9.8k <span>across 14 accounts</span>
          </p>
          <p>
            <em>
              Weekly trend — rendered as a chart by the <code>&lt;Widget&gt;</code>{' '}
              component from this tool's spec in the React deliverable.
            </em>
          </p>
        </article>

        <article className="widget-preview" aria-label="At-risk accounts widget">
          <h3>At-risk accounts</h3>
          {/* PLACEHOLDER: database data — replaced by a MongoDB read once this widget is published */}
          <p>Table · 14 rows · sorted by MRR</p>
          <p>
            <em>
              Rendered as a table by the <code>&lt;Widget&gt;</code> component
              from this tool's spec — see <a href={specUrl}>tool-spec.md</a>.
            </em>
          </p>
        </article>

        <p>
          Drop a widget here — <button type="button">+ Add widget</button>
        </p>
      </section>

      <section className="widget-properties lg:col-start-3 lg:row-start-2 lg:row-span-3" aria-label="Widget properties">
        <h2>Widget properties</h2>
        <form>
          <p>
            <label htmlFor="widget-name">Widget name</label>
            <br />
            <input type="text" id="widget-name" name="widget-name" defaultValue="Revenue at risk" />
          </p>
          <p>
            <label htmlFor="visualisation">Visualisation</label>
            <br />
            <select id="visualisation" name="visualisation" defaultValue="stat_card">
              <option value="stat_card">Stat card (big number + trend bars)</option>
              <option value="bar_chart">Bar chart</option>
              <option value="table">Table</option>
              <option value="calculator">Calculator</option>
            </select>
          </p>
          <p>
            <label htmlFor="date-range">Date range</label>
            <br />
            <select id="date-range" name="date-range" defaultValue="next_30_days">
              <option value="last_7_days">Last 7 days</option>
              <option value="next_30_days">Next 30 days</option>
              <option value="this_quarter">This quarter</option>
              <option value="trailing_12_months">Trailing 12 months</option>
            </select>
          </p>
          <p>
            <label htmlFor="refresh">Refresh</label>
            <br />
            <select id="refresh" name="refresh" defaultValue="hourly">
              <option value="realtime">Realtime</option>
              <option value="hourly">Hourly</option>
              <option value="daily">Daily</option>
            </select>
          </p>
          <fieldset>
            <legend>Client visibility</legend>
            <p>
              <label>
                <input type="radio" name="visibility" value="draft" defaultChecked /> Draft — hidden until published
              </label>
              <br />
              <label>
                <input type="radio" name="visibility" value="published" /> Published — visible in the client portal
              </label>
            </p>
          </fieldset>
          <p>
            <button type="button">Save draft</button>
            <button type="button">Publish to client</button>
          </p>
        </form>
      </section>

      <section className="tool-spec-preview lg:col-span-3" aria-label="Tool spec JSON">
        <h2>Tool spec (JSON)</h2>
        <p>
          This is the data the AI actually returns for the "Revenue at risk"
          widget above — see <a href={specUrl}>tool-spec.md</a> for the
          full format and every field's meaning. I used AI for help with this
          part, I will obviously be studying more about this as I get closer
          to implementing it.
        </p>
        {/* PLACEHOLDER: 3rd-party API — this JSON is what a real Claude API response looks like once the Service deliverable calls it */}
        <pre>
          <code>{spec}</code>
        </pre>
      </section>
    </main>
  );
}
